name: "GitHub Action - rclone"
description: "Commits any changed files and pushes the result back to origin branch."
author: "z-shell"
branding:
  icon: "arrow-up"
  color: "green"
inputs:
  args:
    description: "User name for the commit message"
    required: false

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        RCLONE_CONF: ${{ inputs.args }}
