name: "GitHub Action - rclone"
description: "Commits any changed files and pushes the result back to origin branch."
author: "z-shell"
branding:
  icon: "arrow-up"
  color: "green"
runs:
  using: "docker"
  image: "Dockerfile"
