name: "GitHub Action for git commit"
description: "Commits any changed files and pushes the result back to origin branch."
author: "elstudio"
branding:
  icon: "git-commit"
  color: "green"
inputs:
  wdPath:
    description: "Working directory path"
    required: false
    default: ""
  debug:
    description: "Print script debugging info"
    required: false
    default: "false"
  commitMessage:
    description: "Message to log for this commit"
    required: false
    default: "Regenerate build artifacts."
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        DEBUG: ${{ inputs.debug }}git
        WD_PATH: ${{ inputs.wdPath }}
        COMMIT_MESSAGE: ${{ inputs.commitMessage }}
