---
name: "🆗 Commit"

on: [push]

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: "🆗 Commit"
        uses: z-shell/.github/actions/commit@main
        #  with:
        #    commitMessage: - Optional. Git Commit Message. Defaults to "Regenerate build artifacts."
        #    workDir: - Optional. To specify a directory other than the repository root to check for changed files.
