---
name: "⭕ Trunk Check"
on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    types: [opened, synchronize]
  #schedule:
  #  - cron: 0 04 * * 1-5
  workflow_dispatch: {}

jobs:
  trunk:
    name: "⚡"
    uses: z-shell/.github/.github/workflows/trunk.yml@main
    #secrets:
    #  trunk-token: ${{ secrets.TRUNK_TOKEN }}
    with:
      runs-on: "ubuntu-latest"
      # Pass commands to install or prepare dependencies.
      #get_dependencies: 'sudo apt update && sudo apt install -yq zsh'
      # Pass arguments to run before launching Trunk
      #call_arguments0: ''
      #call_arguments1: ''
      #call_arguments2: ''
      #call_arguments3: ''

      #node_version: '16'
      #npm_arguments: 'npm --version'
      #pnpm_arguments 'pnpm --version'
      #yarn_arguments 'yarn --version'

      # TRUNK:
      # https://docs.trunk.io/get-started
      # https://github.com/trunk-io/trunk-action
      #trunk_path: ''
      #check-mode: ''
      #upload-series: ''
      #arguments: ''
      #cache: ''

      # Pass arguments to run on fail
      #call_on_fail: ''
