---
name: "🚀 Deploy"

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: false
      deploy_key:
        description: 'A token passed from the caller workflow'
        required: false
    inputs:
      username:
        description: '⭐️ Repository owner username'
        required: false
        type: string
      external_repository:
        description: '⭐️ Deploy to external repository'
        required: false
        type: string
      publish_branch:
        default: 'gh-pages'
        description: '⭐️ Set Another GitHub Pages Branch `publish_branch`'
        required: false
        type: string          
      publish_dir:
        default: 'docs'
        description: '⭐️ Source Directory `publish_dir`'
        required: false
        type: string  
      destination_dir:
        description: '⭐️ Deploy to Subdirectory `destination_dir`'
        required: false
        type: string
      exclude_assets:
        description: '⭐️ Filter publishing assets `exclude_assets`'
        required: false
        type: string
      cname:
        description: '⭐️ Add CNAME file `cname`'
        required: false
        type: string  
      keep_files:
        default: 'true'
        description: '⭐️ Keeping existing files `keep_files`'
        required: false
        type: string
      allow_empty_commit:
        default: 'true'
        description: '⭐️ Allow empty commits `allow_empty_commit`'
        required: false
        type: string
      user_name: 
        default: 'digital-teams[bot]'
        description: '⭐️ Set Git username'
        required: false
        type: string
      user_email:
        default: 'digital-teams@pm.me'
        description: '⭐️ Set Git email'
        required: false
        type: string
      full_commit_message:
        description: 'To set a full custom commit message without a triggered commit hash, use the `full_commit_message` option instead of the `commit_message` option.'
        required: false
        type: string
      tag_name:
        description: '⭐️ Create Git tag name'
        required: false
        type: string
      tag_message:
        description: '⭐️ Create Git tag message'
        required: false
        type: string
   
jobs:
  publish:
    if: ${{ github.repository_owner == inputs.username }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
#    strategy:
#      matrix:
#        repo: [z-a-meta-plugins]
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
        with:
          # Default: ${{ github.repository }}
          #repository: 'z-shell/${{ matrix.repo }}'
          ref: 'main'
          # Default: ${{ github.token }}
          #token: '${{ secrets.GH_PAT }}'
          #ssh-key: ''
          # `ssh-keyscan github.com`. The public key for github.com is always implicitly added.
          #ssh-known-hosts: ''
          # `StrictHostKeyChecking=yes` and `CheckHostIP=no` to the SSH command line. Use
          # the input `ssh-known-hosts` to configure additional hosts.
          # Default: true
          #ssh-strict: ''
          # Default: true
          #persist-credentials: ''
          # Relative path under $GITHUB_WORKSPACE to place the repository
          #path: 'docs'
          # Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching
          # Default: true
          clean: 'true'
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: '0'
          # Whether to download Git-LFS files
          # Default: false
          lfs: 'false'
          # When the `ssh-key` input is not provided, SSH URLs beginning with
          # `git@github.com:` are converted to HTTPS.
          #
          # Default: false
          submodules: 'false'
          # Add repository path as safe.directory for Git global config by running `git
          # config --global --add safe.directory <path>`
          # Default: true
          set-safe-directory: 'true'
      - name: '🚀 Deploy'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ secrets.personal_token }}
          deploy_key: ${{ secrets.deploy_key }}
          external_repository: ${{ inputs.external_repository }}'
          publish_branch: ${{ inputs.publish_branch }}
          publish_dir: ${{ inputs.publish_dir }}
          destination_dir: ${{ inputs.destination_dir }}
          exclude_assets: ${{ inputs.exclude_assets }}
          cname: ${{ inputs.cname }}
          keep_files: ${{ inputs.keep_files }}
          allow_empty_commit: ${{ inputs.allow_empty_commit }}
          user_name: ${{ inputs.user_name }}
          user_email: ${{ inputs.full_commit_message }}
          full_commit_message: ${{ inputs
          tag_name: ${{ inputs.tag_name }}
          tag_message: ${{ inputs.tag_message }}
