---
name: "🚀 Deploy Wiki"

on:
  push:
    branches: [ main ]
    tags: ['v*.*.*']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
        id: prepare_tag
        if: startsWith(github.ref, 'refs/tags/')
      - run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          echo "::set-output name=tag_name::${TAG_NAME}"
          echo "::set-output name=deploy_tag_name::deploy-${TAG_NAME}"
#      - name: '🚀 Deploy Wiki'
#        run: 'command git remote add dot-wiki git@github.com:z-shell/wiki.wiki.git'
      - name: '🚀 Deploy Wiki Branch'
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: z-shell/wiki.wiki.git
          publish_branch: wiki
          publish_dir: ./dot-wiki
          cname: wiki.zshell.dev
          keep_files: false
          allow_empty_commit: true
          user_name: digital-teams[bot]
          user_email: digital-teams@pm.me
          full_commit_message: ${{ github.event.head_commit.message }}
          tag_name: ${{ steps.prepare_tag.outputs.deploy_tag_name }}
          tag_message: 'Deployment ${{ steps.prepare_tag.outputs.tag_name }}'
#      - run: |
#          command mkdir -p ~/.ssh
#          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
#          command chmod 600 ~/.ssh/id_ed25519
#      - run: 'command git push --force dot-wiki HEAD:master'
#      - name: Cache
#        uses: actions/cache@v3.0.2
#        with:
#        # A list of files, directories, and wildcard patterns to cache and restore
#          path: 
#          # An explicit key for restoring and saving the cache
#          key: 
#          # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
#          restore-keys: # optional
#          # The chunk size used to split up large files during upload, in bytes
#          upload-chunk-size: # optional
