---
name: "🚀 Deploy"

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      personal_token:
        description: 'A token passed from the caller workflow'
        required: false
      deploy_key:
        description: 'A token passed from the caller workflow'
        required: false
    inputs:
      username:
        description: '⭐️ Repository owner username'
        required: false
        type: string
      external_repository:
        description: '⭐️ Deploy to external repository'
        required: false
        type: string
      publish_branch:
        default: 'gh-pages'
        description: '⭐️ Set Another GitHub Pages Branch `publish_branch`'
        required: false
        type: string          
      publish_dir:
        description: '⭐️ Source Directory `publish_dir`'
        required: false
        type: string  
      destination_dir:
        description: '⭐️ Deploy to Subdirectory `destination_dir`'
        required: false
        type: string
      exclude_assets:
        description: '⭐️ Filter publishing assets `exclude_assets`'
        required: false
        type: string
      cname:
        description: '⭐️ Add CNAME file `cname`'
        required: false
        type: string  
      keep_files:
        default: 'true'
        description: '⭐️ Keeping existing files `keep_files`'
        required: false
        type: string
      allow_empty_commit:
        default: 'true'
        description: '⭐️ Allow empty commits `allow_empty_commit`'
        required: false
        type: string
      user_name: 
        default: 'digital-teams[bot]'
        description: '⭐️ Set Git username'
        required: false
        type: string
      user_email:
        default: 'digital-teams@pm.me'
        description: '⭐️ Set Git email'
        required: false
        type: string
   
jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
        with:
          # Default: ${{ github.repository }}
          #repository: 'z-shell/${{ matrix.repo }}'
          ref: 'main'
          # Default: ${{ github.token }}
          #token: '${{ secrets.GH_PAT }}'
          #ssh-key: ''
          # `ssh-keyscan github.com`. The public key for github.com is always implicitly added.
          #ssh-known-hosts: ''
          # `StrictHostKeyChecking=yes` and `CheckHostIP=no` to the SSH command line. Use
          # the input `ssh-known-hosts` to configure additional hosts.
          # Default: true
          #ssh-strict: ''
          # Default: true
          #persist-credentials: ''
          # Relative path under $GITHUB_WORKSPACE to place the repository
          #path: 'docs'
          # Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching
          # Default: true
          clean: 'true'
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: '0'
          # Whether to download Git-LFS files
          # Default: false
          lfs: 'false'
          # When the `ssh-key` input is not provided, SSH URLs beginning with
          # `git@github.com:` are converted to HTTPS.
          #
          # Default: false
          submodules: 'true'
          # Add repository path as safe.directory for Git global config by running `git
          # config --global --add safe.directory <path>`
          # Default: true
          set-safe-directory: 'true'
      - name: ' 🔖 Prepare tag'
        id: prepare_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          echo "::set-output name=tag_name::${TAG_NAME}"
          echo "::set-output name=deploy_tag_name::deploy-${TAG_NAME}"
      - name: Read .env
        id: read-env
        run: |
          . ./.env
          echo "::set-output name=NODE_VERSION::${NODE_VERSION}"
          echo "::set-output name=HUGO_VERSION::${HUGO_VERSION}"
          echo "::set-output name=GO_VERSION::${GO_VERSION}"
          echo "::set-output name=PYTHON_VERSION::${PYTHON_VERSION}"
          echo "::set-output name=DOCKER_VERSION::${DOCKER_VERSION}"
          echo "::set-output name=ZSH_VERSION::${ZSH_VERSION}"
          echo "::set-output name=RUBY_VERSION::${RUBY_VERSION}"
        if: ${{ steps.hugo-version.outputs.HUGO_VERSION }}
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '${{ steps.hugo-version.outputs.HUGO_VERSION }}'
          extended: true          
      - uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: '🚀 Deploy'
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.personal_token }}
          deploy_key: ${{ secrets.deploy_key }}
          external_repository: ${{ inputs.external_repository }}
          publish_branch: ${{ inputs.publish_branch }}
          publish_dir: ${{ inputs.publish_dir }}
          destination_dir: ${{ inputs.destination_dir }}
          exclude_assets: ${{ inputs.exclude_assets }}
          cname: ${{ inputs.cname }}
          keep_files: ${{ inputs.keep_files }}
          allow_empty_commit: ${{ inputs.allow_empty_commit }}
          user_name: ${{ inputs.user_name }}
          user_email: ${{ inputs.user_email }}
          full_commit_message: ${{ github.event.head_commit.message }}
          tag_name: ${{ steps.prepare_tag.outputs.deploy_tag_name }}
          tag_message: 'Deployment ${{ steps.prepare_tag.outputs.tag_name }}'
