---
name: "🚀 Deploy Wiki"

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: '🚀 Deploy to Wiki'
        run: 'command git remote add dot-wiki git@github.com:z-shell/.github.wiki.git'
#      - run: |
#          command mkdir -p ~/.ssh
#          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
#          command chmod 600 ~/.ssh/id_ed25519
#      - run: 'command git push --force dot-wiki HEAD:master'
#      - name: Cache
#        uses: actions/cache@v3.0.2
#        with:
#        # A list of files, directories, and wildcard patterns to cache and restore
#          path: 
#          # An explicit key for restoring and saving the cache
#          key: 
#          # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
#          restore-keys: # optional
#          # The chunk size used to split up large files during upload, in bytes
#          upload-chunk-size: # optional
#      - name: 🚀 Deploy to Wiki
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: dot-wiki
          keep_files: false
          user_name: digital-teams[bot]
          user_email: digital-teams@pm.me
