---
name: "🚀 Deploy GH Pages"

on:
  workflow_run:
    workflows:
      - "🌀 Z PageSpeed Insights"
      - "🌀 Z Activity"
      - "🌀 Z Metrics"
      - "🌀 Z Reader"
    types:
      - completed
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    defaults:
      run:
        working-directory: metrics
    steps:
      - name: '⤵️ Check out code from GitHub'
        uses: actions/checkout@v3
      - name: '📥 Download SVG artifact'
        uses: actions/download-artifact@v3
        with:
          name: metrics-svg
      - name: '🚀 Deploy to GitHub Pages'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: '.'
          keep_files: true
          user_name: ${{ secrets.ACTIONS_USER }}
          user_email: ${{ secrets.ACTIONS_MAIL }}
