---
name: 🔖 Pull Request Labeler
on:
  pull_request_target:
  workflow_call:
  push:
    paths:
      - .github/lib/labeler.yml
  workflow_dispatch: {}      

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
      - name: ♻️ Fetch Configuration
        run: |
          [[ -d .github ]] || command mkdir .github
          command curl -fsSl https://raw.githubusercontent.com/z-shell/.github/main/.github/lib/labeler.yml -o .github/labeler.yml
      - name: 🚀 Run Labeler          
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GH_PAT }}"
          sync-labels: false
