---
name: "🌀 Z Metrics"
on:
  schedule:
    - cron: "02 02 * * *"
  push:
    paths: [.github/workflows/metrics.yml]
  pull_request:
    paths: [.github/workflows/metrics.yml]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  metrics_svg: metrics/plugin/metrics.svg
  followup_svg: metrics/plugin/followup/followup.svg
  zi_followup_svg: metrics/plugin/followup/zi_followup.svg
  wiki_followup_svg: metrics/plugin/followup/wiki_followup.svg
  f-sy-h_followup_svg: metrics/plugin/followup/f-sy-h_followup.svg

jobs:
  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: metrics    
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: lowlighter/metrics@7e4bab7d85c7d114cc928299765f830c107270a4
        with:
          filename: ${{ env.metrics_svg }}
          token: ${{ secrets.ORG_TOKEN }}
          user: ${{ github.repository_owner }}
      - uses: lowlighter/metrics@7e4bab7d85c7d114cc928299765f830c107270a4
        with:
          filename: ${{ env.followup_svg }}
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          user: ${{ github.repository_owner }}
          plugin_followup: yes
          plugin_followup_indepth: yes
      - uses: lowlighter/metrics@7e4bab7d85c7d114cc928299765f830c107270a4
        with:
          filename: ${{ env.zi_followup_svg }}
          template: repository
          token: ${{ secrets.ORG_TOKEN }}
          user: ${{ github.repository_owner }}
          repo: zi
          plugin_followup: yes
      - uses: lowlighter/metrics@7e4bab7d85c7d114cc928299765f830c107270a4
        with:
          filename: ${{ env.wiki_followup_svg }}
          template: repository
          token: ${{ secrets.ORG_TOKEN }}
          user: ${{ github.repository_owner }}
          repo: wiki
          plugin_followup: yes
      - uses: lowlighter/metrics@7e4bab7d85c7d114cc928299765f830c107270a4
        with:
          filename: ${{ env.f-sy-h_followup_svg }}
          template: repository
          token: ${{ secrets.ORG_TOKEN }}
          user: ${{ github.repository_owner }}
          repo: f-sy-h
          plugin_followup: yes
      - name: "📤 Archive metrics SVG"
        uses: actions/upload-artifact@v3
        with:
          name: metrics-svg
          path: metrics
