---
name: "🌀 Z Metrics"
on:
  schedule:
    - cron: "02 02 * * *"
  push:
    paths: [".github/workflows/metrics.yml"]
  pull_request:
    paths: [".github/workflows/metrics.yml"]
  workflow_dispatch: {}

concurrency:
  group: metrics

jobs:
  metrics:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@e54e5b338fbd6e6cdb5d60f51c22335fc57c401e
      - uses: lowlighter/metrics@26bbaac4a9cf67bce1676e0435eff56fe043e8bc
        with:
          filename: "metrics/metrics.svg"
          token: ${{ secrets.ORG_TOKEN }}
          user: z-shell
      - uses: lowlighter/metrics@26bbaac4a9cf67bce1676e0435eff56fe043e8bc
        with:
          filename: "metrics/plugin/followup/followup.svg"
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          user: z-shell
          plugin_followup: yes
          plugin_followup_indepth: yes
      - uses: lowlighter/metrics@26bbaac4a9cf67bce1676e0435eff56fe043e8bc
        with:
          filename: "metrics/plugin/followup/zi_followup.svg"
          template: repository
          token: ${{ secrets.ORG_TOKEN }}
          user: z-shell
          repo: zi
          plugin_followup: yes
      - uses: lowlighter/metrics@26bbaac4a9cf67bce1676e0435eff56fe043e8bc
        with:
          filename: "metrics/plugin/followup/wiki_followup.svg"
          template: repository
          token: ${{ secrets.ORG_TOKEN }}
          user: z-shell
          repo: wiki
          plugin_followup: yes
      - uses: lowlighter/metrics@26bbaac4a9cf67bce1676e0435eff56fe043e8bc
        with:
          filename: "metrics/plugin/followup/f-sy-h_followup.svg"
          template: repository
          token: ${{ secrets.ORG_TOKEN }}
          user: z-shell
          repo: f-sy-h
          plugin_followup: yes
