---
name: "🌀 Z PageSpeed Insights"
on:
  schedule:
    - cron: "0 3 * * */3"
  push:
    paths: [".github/workflows/pagespeed.yml"]
  pull_request:
    paths: [".github/workflows/pagespeed.yml"]
  workflow_dispatch: {}

concurrency:
  group: metrics

jobs:
  pagespeed:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: lowlighter/metrics@26bbaac4a9cf67bce1676e0435eff56fe043e8bc
        with:
          filename: "metrics/plugin/pagespeed/detailed.svg"
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://wiki.zshell.dev
