---
name: "⭐ Star"
on:
  watch:
  workflow_call:

jobs:
  star:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo -e "\nA :star: from [@${{github.actor}}](https://github.com/${{github.actor}})" >> .github/stars.md
      - uses: z-shell/.github/actions/commit@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUSH_BRANCH: "main"
