---
name: '♻️ Trunk Check'
on:
  workflow_call:
    secrets:
      TRUNK_TOKEN:
        description: 'A Trunk token passed from the caller workflow'
        required: false
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'z-shell'
        required: false
        type: string
      trunk-path:
        description: 'The path is the full path to the trunk launcher'
        required: false
        type: string   
#  env:
#    TRUNK_PATH:
#    TRUNK_CHECK_MODE: all
#    GITHUB_REF_NAME: main
#    GITHUB_REPOSITORY: z-shell
#    GITHUB_SHA: 
#    GITHUB_TOKEN:
#    INPUT_ARGUMENTS: 
#    INPUT_LABEL: 
#    INPUT_TRUNK_TOKEN: 
#    INPUT_UPLOAD_SERIES: 

jobs:
  trunk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#        if: ${{ github.repository_owner == inputs.username }}
      - run: |
          sudo apt update
          sudo apt install -yq zsh
      - uses: trunk-io/trunk-action@v1.0.2     
        with:
          check-mode: all
          trunk-path: ${{ inputs.trunk-path }}
          trunk-token: ${{ secrets.TRUNK_TOKEN }}
