---
name: '♻️ Trunk Check'
on:
  workflow_call:
    secrets:
      TRUNK_TOKEN:
        description: 'A Trunk token passed from the caller workflow'
        required: false
#      PASS_GITHUB_TOKEN:
#        description: 'A GitHub token passed from the caller workflow'
#        required: false
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'z-shell'
        required: false
        type: string
      TRUNK_PATH:
        description: 'The path is the full path to the trunk launcher from the caller workflow'
        required: false
        type: string          
      GITHUB_REF_NAME:
        description: 'GitHub branch or reference from the caller workflow'
        required: false
        type: string  
      TRUNK_CHECK_MODE:
        description: 'Run trunk check on all files in a repo'
        default: 'all'
        required: false
        type: string  
      TRUNK_ARGUMENTS:
        description: 'Pass arguments to trunk from the caller workflow'
        required: false
        type: string  
      INPUT_LABEL:
        description: 'Run multiple Trunk Check jobs on different platforms at the same time, value from the caller workflow'
        required: false
        type: string  
      RUN_ARGS:
        description: 'Pass commands to run from the caller workflow'
        default: 'echo FunnyBunnyWithSomeMoney'
        required: false
        type: string  
      RUN_SHELL:
        description: 'Run in shell specified from the caller workflow'
        default: 'bash'
        required: false
        type: string  

#  env:
#    GITHUB_REPOSITORY: z-shell
#    GITHUB_SHA: 
#    INPUT_LABEL: 
#    INPUT_TRUNK_TOKEN: 
#    INPUT_UPLOAD_SERIES: 

jobs:
  trunk:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: ${{ inputs.RUN_SHELL }}
        working-directory: .
    steps:
      - uses: actions/checkout@v3
#        if: ${{ github.repository_owner == inputs.username }}
      - run: |
          sudo apt update
          sudo apt install -yq zsh
      - run: ${{ inputs.RUN_ARGS }}
      - uses: trunk-io/trunk-action@v1.0.2     
        with:
          trunk-path: ${{ inputs.TRUNK_PATH }}
          trunk-token: ${{ secrets.TRUNK_TOKEN }}
          check-mode: ${{ inputs.TRUNK_CHECK_MODE }}
          arguments: ${{ inputs.TRUNK_ARGUMENTS }}
#        if: ${{ inputs.RUN_NODE }}
#      - uses: actions/setup-node@v3
#        with:
#          node-version: '16'
#      - run: npm install -g bats          
#      - name: My backup step
#        if: ${{ failure() }}
#        uses: actions/WhereIsBunny@1.0.0
#  example_matrix:
#    strategy:
#      matrix:
#        os: [windows-latest, ubuntu-latest]
#        node: [12, 14, 16]
#        include:
#          - os: windows-latest
#            node: 16
#            npm: 6
#    runs-on: ${{ matrix.os }}
#    steps:
#      - uses: actions/setup-node@v3
#        with:
#          node-version: ${{ matrix.node }}
#      - if: ${{ matrix.npm }}
#        run: npm install -g npm@${{ matrix.npm }}
#      - run: npm --version
