---
name: '♻️ Trunk Check'
on:
  workflow_call:
    secrets:
      TRUNK_TOKEN:
        description: 'A Trunk token passed from the caller workflow'
        required: false
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'z-shell'
        required: false
        type: string
      trunk-path:
        description: 'The path is the full path to the trunk launcher'
        default: '.trunk/trunk'
        required: false
        type: string   

jobs:
  trunk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#        if: ${{ github.repository_owner == inputs.username }}
      - run: |
          sudo apt update
          sudo apt install -yq zsh
      - uses: trunk-io/trunk-action@v1.0.1     
        with:
          check-mode: all
          trunk-path: ${{ inputs.trunk-path }}
          trunk-token: ${{ secrets.TRUNK_TOKEN }}
