---
name: '⭕ Trunk Call'
on:
  workflow_call:
    secrets:
      trunk-token:
        description: >
          You can find a per-repo API token in the Trunk web app settings.
          This will cause results to be uploaded to the Trunk web app if this job is a scheduled job running on a branch, or if `check-mode` is set to 'all'.
        required: false
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'z-shell'
        required: false
        type: string
# ===   TRUNK INPUT   === #
      trunk_path:
        description: >
          Path to Trunk Launcher.
          If not provided, we'll look for it the repo root, `.trunk/bin` and `tools/`.
          If it can't be found anywhere and is not provided explicitly, we'll download it on demand."
        required: false
        type: string
      cache:
        default: "true"
        description: >
          Cache trunk downloads and results between runs.
          Caching is only needed when using ephemeral CI runners.
        required: false
        type: string
      upload-series:
        description: >
          Upload series name, for when `trunk-token` is provided. If not provided, we'll use the branch name.
        required: false
        type: string
      check-mode:
        description: >
          Trunk check mode. Leave unset to autodetect just changes.
          Set to 'all' to check the entire repository.
          If `trunk-token` is set with 'all', 'all' will also upload results to the Trunk web app.
        default: 'all'
        required: false
        type: string  
      arguments:
        description: Extra arguments to pass to trunk
        required: false
        type: string        
# ===   TRUNK END   === #
      get_dependencies:
        description: 'Pass required dependencies from the caller workflow'
        default: 'echo '
        required: false
        type: string
      call_arguments1:
        description: 'Pass first arguments from the caller workflow'
        default: 'echo FunnyBunnyWithSomeMoney 1'
        required: false
        type: string 
      call_arguments2:
        description: 'Pass second arguments from the caller workflow'
        default: 'echo FunnyBunnyWithSomeMoney 2'
        required: false
        type: string
      call_arguments3:
        description: 'Pass third arguments from the caller workflow'
        default: 'echo FunnyBunnyWithSomeMoney 3'
        required: false
        type: string        
      shell:
        description: 'Run in shell specified from the caller workflow'
        default: 'bash'
        required: false
        type: string
      working-directory:
        description: 'Run in shell specified from the caller workflow'
        default: '.'
        required: false
        type: string        
      enable_node:
        default: false
        description: 'Enable Node Action'
        required: false
        type: boolean   
      node_version:
        description: 'Set Node versions'
        default: '16'
        required: false
        type: string
      node_arguments:
        description: 'Pass arguments to Node'
        default: 'npm --version'
        required: false
        type: string

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      output0: ${{ steps.step0.outputs.matrix0 }}
      output1: ${{ steps.step1.outputs.matrix1 }}
      output2: ${{ steps.step2.outputs.matrix2 }}
      output3: ${{ steps.step3.outputs.matrix3 }}    
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
        with:
          submodules: recursive
        if: ${{ inputs.node_enable }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
        if: ${{ inputs.node_enable }}
      - run: ${{ inputs.node_arguments1 }}

      - id: step0
        run: echo "::set-output name=matrix0::${{ inputs.get_dependencies }}"      
      - id: step1
        run: |
          MATRIX1="${{ inputs.call_arguments1 }}"
          echo "MATRIX1=${MATRIX1}" >&2
          echo "::set-output name=matrix1::${MATRIX1}"
      - id: step2
        run: |
          MATRIX2="${{ inputs.call_arguments2 }}"
          echo "MATRIX2=${MATRIX2}" >&2
          echo "::set-output name=matrix2::${MATRIX2}"
      - id: step3
        run: |
          MATRIX3="${{ inputs.call_arguments3 }}"
          echo "MATRIX3=${MATRIX3}" >&2
          echo "::set-output name=matrix1::${MATRIX3}"

  setup-node:
    runs-on: ubuntu-latest
    if: ${{ inputs.node_enable }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - run: ${{ inputs.node_arguments1 }}

  trunk-check:
    runs-on: ubuntu-latest
    needs: 
      - build-matrix
      - setup-node
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
      # ===  OUTPUT RUN  === #
      - run: echo ${{needs.build-matrix.outputs.output0}}
      - run: echo ${{needs.build-matrix.outputs.output1}} 
      - run: echo ${{needs.build-matrix.outputs.output2}}
      - run: echo ${{needs.build-matrix.outputs.output3}}

      # ===   TRUNK RUN   === #
      - uses: trunk-io/trunk-action@29e16ed0984c534f2cce634fc991652e5ab572fd 
        with:
          trunk-path: ${{ inputs.trunk_path }}
          trunk-token: ${{ secrets.trunk-token }}
          check-mode: ${{ inputs.check-mode }}
          arguments: ${{ inputs.arguments }}

#          if: ${{ failure() }}
#          run: echo FunnyBunyFailed-NoMoney

#      - name: My backup step
#        if: ${{ failure() }}
#        uses: actions/WhereIsBunny@1.0.0
#  example_matrix:
#    strategy:
#      matrix:
#        os: [windows-latest, ubuntu-latest]
#        node: [12, 14, 16]
#        include:
#          - os: windows-latest
#            node: 16
#            npm: 6
#    runs-on: ${{ matrix.os }}
#    steps:
#      - uses: actions/setup-node@v3
#        with:
#          node-version: ${{ matrix.node }}
#      - if: ${{ matrix.npm }}
#        run: npm install -g npm@${{ matrix.npm }}
#      - run: npm --version
