---
name: '♻️ Trunk Check'
on:
  workflow_call:
    secrets:
      TRUNK_TOKEN:
        description: 'A Trunk token passed from the caller workflow'
        required: false
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'z-shell'
        required: false
        type: string

jobs:
  trunk:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == inputs.username }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt update
          sudo apt install -yq zsh
      - uses: trunk-io/trunk-action@v1.0.1
        with:
          trunk-token: ${{ secrets.TRUNK_TOKEN }}
          check-mode: all
